icons_format = "{icon}"

[theme]
theme = "space-villain"

[icons]
icons = "awesome6"

[[block]]
block = "music"
format = " $icon {$combo.str(max_w:20,rot_interval:0.5) $play $next |}"
player = "spotify"

[[block]]
block = "hueshift"
hue_shifter = "redshift"
step = 50
click_temp = 3500

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = " $icon root: $available.eng(w:2) "

[[block]]
block = "sound"
[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "custom"
command = "setxkbmap -query | grep layout | awk '{print $2}'"
interval = 10

[[block]]
block = "packages"
package_manager = ["pacman"]
interval = 600
format = " $icon $pacman updates available "
format_singular = " $icon $pacman update available "
format_up_to_date = " $icon system up to date "

[[block]]
block = "time"
interval = 5
format = " $timestamp.datetime(f:'%a %d/%m %R') "
[[block.click]]
button = "left"
cmd = "gsimplecal"
